# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true

# Setup
title:               Per Wramdemark
tagline:             'Curious and passionate Java developer'
description:         'I build stuff. With code and people!'
url:                 https://www.wramdemark.se
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Per Wramdemark
  url:               https://twitter.com/perwramdemark
  email:             per@wramdemark.se

# Custom vars
version:             1.0.0

# Google Analytics
google_analytics:    UA-26169584-1