# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true

# Setup
title:               Per Wramdemark
tagline:             'Curious and passionate Java developer'
description:         'A build stuff. With code and people!'
url:                 http://www.wramdemark.se
baseurl:             'https://perwramdemark.github.io'
paginate:            5

# About/contact
author:
  name:              Per Wramdemark
  url:               https://twitter.com/perwramdemark
  email:             per@wramdemark.se

# Custom vars
version:             1.0.0